apiVersion: v1
kind: Pod
metadata:
  name: single-a
  annotations:
    scheduler.example.com/priority: "50"
spec:
  schedulerName: secondary-scheduler
  containers:
    - name: pause
      image: registry.k8s.io/pause:3.9
